config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles, param: :title
  resources :categories, only: [:index, :new, :create]
  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  validates :title, presence: true, uniqueness: {case_sensitive: false}
  validates :content, presence: true

  def self.all_ordered_articles
    Article.all.order("created_at DESC")
  end

  def self.articles_of_category(category)
    Article.where(category_id: category.id).order("created_at DESC")
  end

  def to_param
    title
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles

  validates :name, uniqueness: {case_sensitive: false}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @categories = Category.all
    if params[:category].blank?
      @articles = Article.all_ordered_articles
    else
      @category = Category.find_by(name: params[:category])
      @articles = Article.articles_of_category(@category)
    end
  end

  def show
    @article = find_article
    @category = Category.find_by(id: @article.category_id)
  end

	def new
    @article = current_user.articles.build
	end

	def create
		@article = current_user.articles.build(article_params)
		return redirect_to @article if @article.save
    flash[:notice] = 'Error in form'
		render 'new'
	end

  def edit
    @article = find_article
  end

  def update
    @article = find_article
    return redirect_to @article if @article.update(article_params)
    flash[:notice] = 'Error in form'
    render 'edit'
  end

  def destroy
    @article = find_article
    return redirect_to @article unless current_user.id == @article.user_id
    @article.destroy
    redirect_to root_path
  end

	private

	def article_params
		params.require(:article).permit(:title, :content, :category_id)
	end

  def find_article
    Article.find_by(title: params[:title])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to action: "index"
    else
      render 'new'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/articles/_form.html.haml
= simple_form_for @article do |f|
  = f.collection_select :category_id, Category.all, :id, :name, { prompt: "Choose a Category" }
  = f.input :title
  = f.input :content
  = f.submit class: "btn btn-default"

app/views/articles/edit.html.haml
%h1 Edit Article

= render 'form'
.btn-group
  = link_to "Back", article_path, class: "btn btn-default"

app/views/articles/index.html.haml
.row
  .col-md-9
    - if @category
      %h3= @category.name +  " Wiki's"
    - @articles.each do |article|
      %h2= link_to article.title, article
      %p= truncate(markdown(article.content), length:200)
      %p
        Published at
        = article.created_at.strftime('%I:%M%p, %b %d, %Y')
  .col-md-3
    %h2
      %li= link_to "Categories", categories_path, class: "list-group-item"
    %p
      %li= link_to "new", new_category_path, class:  "list-group-item"
    = render '/categories/categories', categories: @categories

app/views/articles/new.html.haml
%h1 New Article

= render 'form'

= link_to "Back", root_path

app/views/articles/show.html.haml
%h2= @article.title
%p= markdown(@article.content)
%p= link_to("#{@category.name}", "/articles?category=#{@category.name}")

- if user_signed_in?
  .btn-group
    = link_to "Edit", edit_article_path, class: "btn btn-default"
    -if current_user.id == @article.user_id
      = link_to "Delete", article_path(@article), method: :delete, class: "btn btn-danger"

app/views/categories/_categories.html.haml
- @categories.each do |category|
  %li= link_to category.name, articles_path(category: category.name), class: "list-group-item"

app/views/categories/_form.html.haml
= simple_form_for @category do |f|
  = f.input :name
  = f.submit class: "btn btn-default"

app/views/categories/index.html.haml
= render 'categories'

= link_to "New", new_category_path

app/views/categories/new.html.haml
%h1 New Category

= render 'form'

= link_to "Back", categories_path

app/views/layouts/application.html.haml
!!!
%html
%head
  %title
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    = link_to "Wiki", root_path, class: "navbar-brand"
    %ul.nav.navbar-nav.navbar-right
      - if user_signed_in?
        %li= link_to "New Article", new_article_path
        %li= link_to "Sign Out", destroy_user_session_path, method: :delete
      - else
        %li= link_to "Sign In", new_user_session_path
        %li= link_to "Sign Up", new_user_registration_path

%p.notice= notice
%p.alert= alert

.container
  = yield